name: Release Charts

on:
  push:
    branches:
      - main

permissions:
  contents: write # publish chart to gh-pages branch
  packages: write # publish chart to ghcr.io

jobs:
  release-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.9.0

      # Publish OCI charts to ghcr.io
      - name: Generate charts
        run: |
          mkdir -p .cr-release-packages
          for d in charts/* ; do
            helm package "$d" --destination .cr-release-packages
          done

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Charts to GHCR
        run: |
          for pkg in .cr-release-packages/*; do
            echo ${pkg}
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" oci://ghcr.io/hungran/http-echo-helm-chart
          done

  release-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.9.0
          
      # Publish charts to gh-pages branch
      - name: Publish charts to GitHub Pages
        uses: helm/chart-releaser-action@v1.5.0
        with:
          config: .github/configs/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

